##Numpy Samples

In [1]:
import numpy as np

In [2]:
x = np.float32(1.0)

In [3]:
x

1.0

In [4]:
y = np.int_([1,2,4])

In [5]:
y

array([1, 2, 4])

In [7]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [8]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [9]:
np.linspace(1., 4., 7)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [11]:
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
b = np.arange(27).reshape(3,3,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [14]:
b[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [15]:
b[0,2]

array([6, 7, 8])

In [16]:
b[1,2]

array([15, 16, 17])

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[2:5]

array([2, 3, 4])

In [19]:
x[:-7]

array([0, 1, 2])

In [20]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
a = np.arange(5)
b = np.arange(5)
print(a)
print(b)

[0 1 2 3 4]
[0 1 2 3 4]


In [23]:
a+b

array([0, 2, 4, 6, 8])

In [24]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [25]:
a > 3

array([False, False, False, False,  True])

In [26]:
10*np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [27]:
a*2

array([0, 2, 4, 6, 8])

In [28]:
np.dot(1,b)

array([0, 1, 2, 3, 4])

In [29]:
np.dot(a,b)

30

In [31]:
a = np.random.random((2,3))
a

array([[0.15228145, 0.36158674, 0.73138365],
       [0.67727048, 0.21669858, 0.8579154 ]])

In [32]:
a.sum()

2.9971363172292866

In [33]:
a.min()

0.15228145213250865

In [34]:
a.max()

0.8579153992942428

In [35]:
a.max(axis=0)

array([0.67727048, 0.36158674, 0.8579154 ])

In [36]:
a.max(axis=1)

array([0.73138365, 0.8579154 ])

In [37]:
a = np.floor(10*np.random.random((3,4)))
a

array([[0., 8., 9., 9.],
       [6., 4., 8., 0.],
       [0., 0., 0., 4.]])

In [38]:
a.shape

(3, 4)

In [39]:
a.shape = (6,2)

In [40]:
a

array([[0., 8.],
       [9., 9.],
       [6., 4.],
       [8., 0.],
       [0., 0.],
       [0., 4.]])

In [41]:
a.tranpose()

AttributeError: 'numpy.ndarray' object has no attribute 'tranpose'

In [42]:
a.transpose()

array([[0., 9., 6., 8., 0., 0.],
       [8., 9., 4., 0., 0., 4.]])

In [43]:
from numpy.linalg import *

In [46]:
a = 10*np.random.random((2,2))
a

array([[2.96723034, 0.59341062],
       [5.6934158 , 3.84914922]])

In [47]:
inv(a)

array([[ 0.47858449, -0.07378179],
       [-0.70789162,  0.36893098]])